---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 欧阳.
--- DateTime: 2023-04-13 14:52
---
---override spawn
local util = require("util")
util.hotfix_ex(CS.SpawnObstacle,'Spawn',function(self)
    if CS.GameManager.Instance.isGameOver==false then
        self:Spawn();
    end
end)

--register restart button
CS.UnityEngine.Debug.Log("Register Button")
CS.GameManager.Instance.restartBtn.onClick:AddListener(function(self)
    CS.UnityEngine.SceneManagement.SceneManager.LoadScene("Main")
end
);


--mounting game hard

xlua.hotfix(CS.GameManager, 'Update', function(self)
    if  self.spawnObstacle.spawnCd>1 then
        self.spawnObstacle.spawnCd = self.spawnObstacle.spawnCd- CS.UnityEngine.Time.deltaTime/10
    end
    if self.spawnObstacle.obstacleSpeed>-10 then
        self.spawnObstacle.obstacleSpeed = self.spawnObstacle.obstacleSpeed- CS.UnityEngine.Time.deltaTime/10
    end
    if self.strollBackGround.strollSpeed>-10 then
        self.strollBackGround.strollSpeed =  self.strollBackGround.strollSpeed-CS.UnityEngine.Time.deltaTime/10
    end
end)

--[[
util.hotfix_ex(CS.StrollBackGround,'Update',function(self)
    if self.strollSpeed < -10 then
       self:Update();
        self.strollSpeed = self.strollSpeed- CS.UnityEngine.Time.deltaTime
    end
end)
--]]