---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 欧阳.
--- DateTime: 2023-04-13 16:22
---

--ResourceUpdate 
CS.UnityEngine.Debug.Log("Load Resource")
CS.ResourceLoader.SetBgmPackName("bgm");
CS.ResourceLoader.SetSoundPackName("clip");
CS.ResourceLoader.SetObstaclePackName("obstacle");
CS.ResourceLoader:LazyLoadInit();

